<p>
Variations for <i>Anopheles gambiae</i> were imported from <a href="http://www.ncbi.nlm.nih.gov/projects/SNP/">NCBI dbSNP</a> and from the 
M & S molecular form genome sequencing project analysis. 
</p>

<p>Variation data provided by this site were also imported from the following studies.

<ul>
<li><p>
    <a>SNP genotyping defines complex gene-flow boundaries among African malaria vector mosquitoes</a> by <a href="http://www.ncbi.nlm.nih.gov/pubmed/20966254">Neafsey et al</a>
    </p>
</li>
<li><p>
    <a>Association mapping of insecticide resistance in wild Anopheles gambiae populations</a> by <a href="http://www.ncbi.nlm.nih.gov/pubmed/20976111">Donnelly et al.</a>
    </p>
</li>
<li><p>
    <a>Gene flow-dependent genomic divergence between Anopheles gambiae M and S forms</a> by <a href="http://www.ncbi.nlm.nih.gov/pubmed/21836185">Donnelly et al.</a>
   </p>
</li>
<li><p>
    <a>Anopheles gambiae Genome Variation Project (release 0.1)</a> by <a href="http://www.sanger.ac.uk/research/projects/malariaprogramme-kwiatkowski/#t_research">Kwiatkowski group, Welcome Trust Sanger Institute.</a>
    </p>
</li>
</ul>

</p>
