<span id="vb_logo"> 	      <a href="/">
<img src="/img/vectorbase_logo.png"  alt="VectorBase" title="VectorBase" 
align="right" /></a>
</span>
<span>VectorBase is an <a href="http://www.pathogenportal.net">NIAID funded Bioinformatics Resource Center</a> 
focused on invertebrate vectors of human pathogens.
</span>
</p>
<a href="http://www.ensembl.org/info/about/intro.html"><IMG SRC="http://www.ensembl.org/img/empowered.png" 
ALT="Powered by Ensembl" /></a>

