<h2 class="first">Featured content</h2>
<p>
<img src="/img/species/Featured_content_VB2011_02.png" style="height:70px;width:70px" class="float-left" alt="Rhodnius prolixus" title="Rhodnius prolixus (triatomid bug)" />
<i>Rhodnius prolixus</i> is an important vector for Chagas disease, which is caused by the single-celled parasite <i>Trypanosoma cruzi</i>. 
Infection commonly takes place when the parasite is shed in feces by <i>Rhodnius prolixus</i> immediately after a blood meal.  Chagas disease affects 8-10 million people 
living in Central and Southern America, and causes 20,000 to 50,000 deaths annually.  There is no vaccine for Chagas disease.
</p>
